In [1]:
import numpy as np
from matplotlib import pyplot as plt
from sklearn import preprocessing
import wfdb
import copy as cp
import scipy.signal as signal
import pickle
from sklearn import preprocessing
from tqdm import tqdm
import os
import re
import pandas as pd
import csv

from sklearn.linear_model import LogisticRegression
from sklearn import neighbors
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifer
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from time import time
import timeit


In [2]:
record_list = [] # Initialize the array that will hold the list of our records

records = 'mit-bih-dataframes/subject_list.csv' # Get our record list like we did in the initial extraction
with open(records) as rfile:# Load our records into the array
    for record in rfile:
        record = record[0:-1] # The -1 removes the newline ("\n") character from the string
        record_list.append(record)

In [3]:
dfdic = {}
for idx, x in enumerate(record_list):
    dfdic[x] = pd.read_csv('mit-bih-features/'+x+ '.csv', index_col=0)
    

In [4]:
subject_df = pd.DataFrame()
for idx, x in enumerate(record_list):
    subject_df = pd.concat([subject_df, dfdic[x]])
subject_df = subject_df.drop(["Unnamed: 0.1"], axis=1)

In [5]:
#for idx, x in enumerate(subject_df["rhythmLabel"]):
    #if x=="Normal" or x=="Other":
        #subject_df["rhythmLabel"][idx]="Non-Afib"
        

In [6]:
subject_df['Mappedrhythmlabels'] = subject_df['rhythmLabel'].map({'Normal':0, 'Other':0, 'AFIB':1})

In [7]:
subject_df.head()

subsetID rhythmLabel      StoS      StoR      StoL      RtoS      RtoR  \
0  04015-0.csv      Normal  0.200000  0.057143  0.028571  0.057143  0.228571   
1  04015-1.csv      Normal  0.000000  0.052632  0.000000  0.052632  0.184211   
2  04015-2.csv      Normal  0.333333  0.083333  0.055556  0.027778  0.305556   
3  04015-3.csv      Normal  0.300000  0.175000  0.000000  0.125000  0.025000   
4  04015-4.csv      Normal  0.090909  0.151515  0.090909  0.030303  0.060606   

       RtoL      LtoS      LtoR      LtoL         RMS        STD   CoefVar  \
0  0.142857  0.057143  0.114286  0.114286  156.276998  43.660906  0.248152   
1  0.236842  0.000000  0.210526  0.263158  197.783973  57.233572  0.355262   
2  0.083333  0.111111  0.000000  0.000000  151.638551  43.820505  0.253179   
3  0.125000  0.075000  0.050000  0.125000  157.611865  48.827831  0.318730   
4  0.212121  0.212121  0.060606  0.090909  226.855681  53.260256  0.289227   

   Range    IQR   MAD  Mappedrhythmlabels  
0  155.0  78.00  32.5                   0  
1  213.0  93.50  55.0                   0  
2  138.0  72.00  56.0                   0  
3  167.0  79.00  59.0                   0  
4  237.0  95.75  66.5                   0

In [8]:
#Logistic Regression

kf = KFold(n_splits=5, random_state=3, shuffle=True)
model = LogisticRegression(solver='liblinear')

start_time = timeit.default_timer()

acc_score = []
Truth = []
Output = []

for train_index, test_index in kf.split(subject_df): 
    #X_train = subject_df.loc[train_index, ["StoS", "StoR", "StoL", "RtoS", "RtoR", "RtoL","LtoS", "LtoR", "LtoL"]]
    #X_test = subject_df.loc[test_index, ["StoS", "StoR", "StoL", "RtoS", "RtoR", "RtoL","LtoS", "LtoR", "LtoL"]]
    #Y_train = subject_df.loc[train_index, "rhythmLabel"]
    #Y_test = subject_df.loc[test_index, "rhythmLabel"]
    
    X_train = subject_df.iloc[train_index, 2:11]
    X_test = subject_df.iloc[test_index, 2:11]
    Y_train = subject_df.iloc[train_index, -1]
    Y_test = subject_df.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))


---Run time is 0.6074776120000003 seconds ---

Accuracy of each fold: 
 [0.9246649206593746, 0.9283513097072419, 0.9312788906009245, 0.9306625577812019, 0.9343605546995377]
Avg accuracy: 0.929863646689656
Std of accuracy : 
0.003230395375065387

[[18564   862]
 [ 1414 11611]]

              precision    recall  f1-score   support

           0       0.93      0.96      0.94     19426
           1       0.93      0.89      0.91     13025

    accuracy                           0.93     32451
   macro avg       0.93      0.92      0.93     32451
weighted avg       0.93      0.93      0.93     32451



In [9]:
print(x)

08455


In [10]:
#LDA
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model=LinearDiscriminantAnalysis()

for train_index, test_index in kf.split(subject_df):
    X_train = subject_df.iloc[train_index, 2:11]
    X_test = subject_df.iloc[test_index, 2:11]
    Y_train = subject_df.iloc[train_index, -1]
    Y_test = subject_df.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))
    

---Run time is 3.336531547 seconds ---

Accuracy of each fold: 
 [0.9246649206593746, 0.9283513097072419, 0.9312788906009245, 0.9306625577812019, 0.9343605546995377, 0.9177322446464335, 0.923728813559322, 0.9265023112480739, 0.9265023112480739, 0.9275808936825886]
Avg accuracy: 0.9271364807832772
Std of accuracy : 
0.004363692689126554

[[37274  1578]
 [ 3151 22899]]

              precision    recall  f1-score   support

           0       0.92      0.96      0.94     38852
           1       0.94      0.88      0.91     26050

    accuracy                           0.93     64902
   macro avg       0.93      0.92      0.92     64902
weighted avg       0.93      0.93      0.93     64902



In [11]:
#QDA
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model=QuadraticDiscriminantAnalysis()

for train_index, test_index in kf.split(subject_df):
    X_train = subject_df.iloc[train_index, 2:11]
    X_test = subject_df.iloc[test_index, 2:11]
    Y_train = subject_df.iloc[train_index, -1]
    Y_test = subject_df.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

/Users/SAHIL/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:808: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/SAHIL/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:808: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/SAHIL/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:808: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/SAHIL/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:808: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/Users/SAHIL/opt/anaconda3/lib/python3.8/site-packages/sklearn/discriminant_analysis.py:808: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


---Run time is 7.237539179999999 seconds ---

Accuracy of each fold: 
 [0.9246649206593746, 0.9283513097072419, 0.9312788906009245, 0.9306625577812019, 0.9343605546995377, 0.9177322446464335, 0.923728813559322, 0.9265023112480739, 0.9265023112480739, 0.9275808936825886, 0.9074102603604991, 0.910477657935285, 0.9112480739599383, 0.9121725731895224, 0.9149460708782743]
Avg accuracy: 0.9218412962770862
Std of accuracy : 
0.008412053656872118

[[54909  3369]
 [ 4240 34835]]

              precision    recall  f1-score   support

           0       0.93      0.94      0.94     58278
           1       0.91      0.89      0.90     39075

    accuracy                           0.92     97353
   macro avg       0.92      0.92      0.92     97353
weighted avg       0.92      0.92      0.92     97353



In [15]:
#KNN-CV
KNN_result = []
X=subject_df[["StoS", "StoR", "StoL", "RtoS", "RtoR", "RtoL","LtoS", "LtoR", "LtoL"]]
Y=subject_df["Mappedrhythmlabels"]
crossvalidation = KFold(n_splits=5, random_state=3, shuffle=True)
KNNResult = []
for k in range(1,26):
    knn = neighbors.KNeighborsClassifier(n_neighbors=k)
    model = knn.fit(X, Y)
    scores=cross_val_score(model, X, Y, cv=crossvalidation)
    print('Accuracy of each fold: \n {}'.format(scores))
    print()
    print("Avg accuracy: {}".format(scores.mean()))
    KNN_result.append(scores.mean())
print(KNN_result)

Accuracy of each fold: 
 [0.93144354 0.93420647 0.93297381 0.93420647 0.93405239]

Avg accuracy: 0.9333765348678827
Accuracy of each fold: 
 [0.92235403 0.92557781 0.92619414 0.93004622 0.92804314]

Avg accuracy: 0.9264430707541246
Accuracy of each fold: 
 [0.94284394 0.94637904 0.9440678  0.94653313 0.94791988]

Avg accuracy: 0.945548756735354
Accuracy of each fold: 
 [0.94053305 0.9431433  0.94237288 0.94668721 0.94360555]

Avg accuracy: 0.9432683965163097
Accuracy of each fold: 
 [0.94453859 0.94730354 0.94637904 0.94699538 0.94992296]

Avg accuracy: 0.9470279032791403
Accuracy of each fold: 
 [0.94315206 0.94745763 0.94761171 0.94853621 0.94915254]

Avg accuracy: 0.9471820292124284
Accuracy of each fold: 
 [0.94469265 0.94853621 0.94822804 0.94884438 0.95007704]

Avg accuracy: 0.9480756643250736
Accuracy of each fold: 
 [0.94361424 0.94838213 0.94745763 0.94853621 0.94961479]

Avg accuracy: 0.9475209980204902
Accuracy of each fold: 
 [0.94500077 0.94761171 0.94637904 0.94699538 0.9

In [18]:
#KNN-CV
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model=neighbors.KNeighborsClassifier(n_neighbors=7)

for train_index, test_index in kf.split(subject_df): 
    X_train = subject_df.iloc[train_index, 2:11]
    X_test = subject_df.iloc[test_index, 2:11]
    Y_train = subject_df.iloc[train_index, -1]
    Y_test = subject_df.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

---Run time is 924.891676309 seconds ---

Accuracy of each fold: 
 [0.9246649206593746, 0.9283513097072419, 0.9312788906009245, 0.9306625577812019, 0.9343605546995377, 0.9177322446464335, 0.923728813559322, 0.9265023112480739, 0.9265023112480739, 0.9275808936825886, 0.9074102603604991, 0.910477657935285, 0.9112480739599383, 0.9121725731895224, 0.9149460708782743, 0.9446926513634263, 0.9485362095531588, 0.9482280431432973, 0.9488443759630201, 0.9500770416024653, 0.9446926513634263, 0.9485362095531588, 0.9482280431432973, 0.9488443759630201, 0.9500770416024653]
Avg accuracy: 0.932335043496281
Std of accuracy : 
0.014454681117413316

[[91719  5411]
 [ 5568 59557]]

              precision    recall  f1-score   support

           0       0.94      0.94      0.94     97130
           1       0.92      0.91      0.92     65125

    accuracy                           0.93    162255
   macro avg       0.93      0.93      0.93    162255
weighted avg       0.93      0.93      0.93    162255

